# Generated by Django 5.2.3 on 2025-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyItem',
            fields=[
                ('deptID', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
            ],
        ),
    ]
